# A Catppuccin RC file for Helix. In beta, specs may change.
app_name: Helix # name of app
binary_name: hx # name of executably
install_location:
  unix: ~/.config/helix/
  windows: "%appdata%/helix/"
installation: # Install instructions
  flavours: # Specific flavours
    all:
      default:
        - themes/default
      additional:
        no-italics:
          - themes/no-italics
    latte:
      default: # Default and no-italic variants
        - themes/default/catppuccin_latte.toml
      additional:
        no-italics:
          - themes/no-italics/catppuccin_latte.toml
    frappe:
      default:       
        - themes/default/catppuccin_frappe.toml
      additional:
        no-italics:
          - themes/no-italics/catppuccin_frappe.toml
    macchiato:
      default:
        - themes/default/catppuccin_macchiato.toml
      additional:
        no-italics:
          - themes/no-italics/catppuccin_macchiato.toml
    mocha:
      default:
        - themes/default/catppuccin_mocha.toml
      additional:
        no-italics:
          - themes/no-italics/catppuccin_mocha.toml
  to: themes/ # Install location
  one_flavour: false # Only one flavour?
  modes: # Additional modes
    - no-italics
